apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YmFja3Vwcy11c2Vy
  AWS_SECRET_ACCESS_KEY: ZWN5dUtMclJBYg==
  AWS_ENDPOINTS: aHR0cDovL21pbmlvLm1pbmlvLnN2Yy5jbHVzdGVyLmxvY2FsOjkwMDA=
  #AWS_CERT: your base64 encoded custom CA certificate goes here
