apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  creationTimestamp: '2023-06-28T22:36:56Z'
  generation: 3
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:description: {}
          f:destinations: {}
          f:sourceRepos: {}
        f:status: {}
      manager: argocd-server
      operation: Update
      time: '2023-06-28T22:43:45Z'
  name: microservices
  namespace: argocd
  resourceVersion: '16076316'
  uid: fdb943a7-15d9-43e0-a2a4-e2cc9b12de11
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/appprojects/microservices
status: {}
spec:
  description: microservices projects
  destinations:
    - name: '*'
      namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
