apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-backup-elastic  
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/elastic
    server: 192.168.0.150	
---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-minio
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/minio
    server: 192.168.0.150	
---