- name: Installing NFS server
  hosts: commands
  gather_facts: False

  tasks:
    - name: Apply argocd project manifests
      command: kubectl apply -f "{{ item }}"
      with_fileglob:
        - "./argocd/projects/*.yaml"

    - name: Apply argocd repositories manifests
      command: kubectl apply -f "{{ item }}"
      with_fileglob:
        - "./argocd/repositories/*.yaml"

    - name: Apply argocd applications manifests
      command: kubectl apply -f "{{ item }}"
      with_fileglob:
        - "./argocd/applications/*.yaml"