- name: Installing NFS server
  hosts: commands
  gather_facts: False

  tasks:
    - name: Apply argocd projects manifests
      command: kubectl apply -f "{{ item }}"
      with_fileglob:
        - "cluster/argocd/projects/*.yaml"