- name: Installing NFS server
  hosts: commands
  gather_facts: False

  tasks:
    - name: Apply argocd project manifests
      command: kubectl apply -f "{{ item }}"
      with_fileglob:
        - "\argocd\projects\"

    - name: Apply argocd repositories manifests
      command: kubectl apply -f "{{ item }}"
      with_fileglob:
        - "\argocd\repositories\"

    - name: Apply argocd applications manifests
      command: kubectl apply -f "{{ item }}"
      with_fileglob:
        - "\argocd\applications\"