apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:        
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  ingressClassName: nginx
  rules:
  - host: longhorn.binesty.corp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
---

apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: bG9uZ2hvcm4tdXNlcg==
  AWS_SECRET_ACCESS_KEY: ZWN5dUtMclJBYg==
  AWS_ENDPOINTS: aHR0cDovL21pbmlvLXNlcnZpY2UubWluaW8uc3ZjLmJpbmVzdHk6OTA5MA==
  #AWS_CERT: your base64 encoded custom CA certificate goes here