apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:        
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: longhorn-ingress
  namespace: longhorn-system
spec:
  ingressClassName: nginx
  rules:
  - host: longhorn.binesty.corp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
---

apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YWRtaW4= # admin
  AWS_SECRET_ACCESS_KEY: NzBmN3Y1ZjlPMg== # 70f7v5f9O2
  AWS_ENDPOINTS: aHR0cDovL21pbmlvLm1pbmlvLnN2Yy5iaW5lc3R5OjkwMDA= # http://minio.minio.svc.binesty:9000
  #AWS_CERT: LS0tL
---