apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: cheap
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.30-192.168.0.30
---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: binesty-net
  namespace: metallb-system
spec:
  ipAddressPools:
  - cheap