apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"creationTimestamp":"2024-04-03T00:34:45Z","generation":16,"labels":{"source":"external"},"managedFields":[{"apiVersion":"argoproj.io/v1alpha1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:source":{}}},"f:spec":{".":{},"f:destination":{".":{},"f:namespace":{},"f:server":{}},"f:project":{},"f:source":{".":{},"f:chart":{},"f:helm":{".":{},"f:parameters":{}},"f:repoURL":{},"f:targetRevision":{}},"f:syncPolicy":{".":{},"f:automated":{},"f:syncOptions":{}}},"f:status":{".":{},"f:health":{},"f:summary":{},"f:sync":{".":{},"f:comparedTo":{".":{},"f:destination":{},"f:source":{}}}}},"manager":"argocd-server","operation":"Update","time":"2024-04-03T00:35:01Z"},{"apiVersion":"argoproj.io/v1alpha1","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:controllerNamespace":{},"f:health":{"f:status":{}},"f:history":{},"f:operationState":{".":{},"f:finishedAt":{},"f:message":{},"f:operation":{".":{},"f:initiatedBy":{".":{},"f:automated":{}},"f:retry":{".":{},"f:limit":{}},"f:sync":{".":{},"f:revision":{},"f:syncOptions":{}}},"f:phase":{},"f:startedAt":{},"f:syncResult":{".":{},"f:resources":{},"f:revision":{},"f:source":{".":{},"f:chart":{},"f:helm":{".":{},"f:parameters":{}},"f:repoURL":{},"f:targetRevision":{}}}},"f:reconciledAt":{},"f:resources":{},"f:sourceType":{},"f:summary":{"f:images":{}},"f:sync":{"f:comparedTo":{"f:destination":{"f:namespace":{},"f:server":{}},"f:source":{"f:chart":{},"f:helm":{".":{},"f:parameters":{}},"f:repoURL":{},"f:targetRevision":{}}},"f:revision":{},"f:status":{}}}},"manager":"argocd-application-controller","operation":"Update","time":"2024-04-03T00:43:26Z"}],"name":"redis","namespace":"argocd","resourceVersion":"111088","selfLink":"/apis/argoproj.io/v1alpha1/namespaces/argocd/applications/redis","uid":"0ff1e6e8-72c5-49af-b07d-3619ecf44312"},"spec":{"destination":{"namespace":"redis","server":"https://kubernetes.default.svc"},"project":"infrastructure","source":{"chart":"redis","helm":{"parameters":[{"name":"auth.password","value":"chageme"},{"name":"sentinel.enabled","value":"true"}]},"repoURL":"https://charts.bitnami.com/bitnami","targetRevision":"19.0.2"},"syncPolicy":{"automated":{},"syncOptions":["CreateNamespace=true"]}},"status":{"controllerNamespace":"argocd","health":{"status":"Healthy"},"history":[{"deployStartedAt":"2024-04-03T00:34:46Z","deployedAt":"2024-04-03T00:34:48Z","id":0,"revision":"19.0.2","source":{"chart":"redis","helm":{"parameters":[{"name":"auth.password","value":"chageme"},{"name":"sentinel.enabled","value":"true"}]},"repoURL":"https://charts.bitnami.com/bitnami","targetRevision":"19.0.2"}}],"operationState":{"finishedAt":"2024-04-03T00:34:48Z","message":"successfully
      synced (all tasks
      run)","operation":{"initiatedBy":{"automated":true},"retry":{"limit":5},"sync":{"revision":"19.0.2","syncOptions":["CreateNamespace=true"]}},"phase":"Succeeded","startedAt":"2024-04-03T00:34:46Z","syncResult":{"resources":[{"group":"networking.k8s.io","hookPhase":"Running","kind":"NetworkPolicy","message":"networkpolicy.networking.k8s.io/redis
      created","name":"redis","namespace":"redis","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Running","kind":"ServiceAccount","message":"serviceaccount/redis
      created","name":"redis","namespace":"redis","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Running","kind":"Secret","message":"secret/redis
      created","name":"redis","namespace":"redis","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Running","kind":"ConfigMap","message":"configmap/redis-configuration
      created","name":"redis-configuration","namespace":"redis","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Running","kind":"ConfigMap","message":"configmap/redis-health
      created","name":"redis-health","namespace":"redis","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Running","kind":"ConfigMap","message":"configmap/redis-scripts
      created","name":"redis-scripts","namespace":"redis","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Running","kind":"Service","message":"service/redis-headless
      created","name":"redis-headless","namespace":"redis","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Running","kind":"Service","message":"service/redis
      created","name":"redis","namespace":"redis","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"apps","hookPhase":"Running","kind":"StatefulSet","message":"statefulset.apps/redis-node
      created","name":"redis-node","namespace":"redis","status":"Synced","syncPhase":"Sync","version":"v1"}],"revision":"19.0.2","source":{"chart":"redis","helm":{"parameters":[{"name":"auth.password","value":"chageme"},{"name":"sentinel.enabled","value":"true"}]},"repoURL":"https://charts.bitnami.com/bitnami","targetRevision":"19.0.2"}}},"reconciledAt":"2024-04-03T00:43:26Z","resources":[{"kind":"ConfigMap","name":"redis-configuration","namespace":"redis","status":"Synced","version":"v1"},{"kind":"ConfigMap","name":"redis-health","namespace":"redis","status":"Synced","version":"v1"},{"kind":"ConfigMap","name":"redis-scripts","namespace":"redis","status":"Synced","version":"v1"},{"kind":"Secret","name":"redis","namespace":"redis","status":"Synced","version":"v1"},{"health":{"status":"Healthy"},"kind":"Service","name":"redis","namespace":"redis","status":"Synced","version":"v1"},{"health":{"status":"Healthy"},"kind":"Service","name":"redis-headless","namespace":"redis","status":"Synced","version":"v1"},{"kind":"ServiceAccount","name":"redis","namespace":"redis","status":"Synced","version":"v1"},{"group":"apps","health":{"message":"statefulset
      rolling update complete 3 pods at revision
      redis-node-5db9569bdc...","status":"Healthy"},"kind":"StatefulSet","name":"redis-node","namespace":"redis","status":"Synced","version":"v1"},{"group":"networking.k8s.io","kind":"NetworkPolicy","name":"redis","namespace":"redis","status":"Synced","version":"v1"}],"sourceType":"Helm","summary":{"images":["docker.io/bitnami/redis-sentinel:7.2.4-debian-12-r7","docker.io/bitnami/redis:7.2.4-debian-12-r9"]},"sync":{"comparedTo":{"destination":{"namespace":"redis","server":"https://kubernetes.default.svc"},"source":{"chart":"redis","helm":{"parameters":[{"name":"auth.password","value":"chageme"},{"name":"sentinel.enabled","value":"true"}]},"repoURL":"https://charts.bitnami.com/bitnami","targetRevision":"19.0.2"}},"revision":"19.0.2","status":"Synced"}}}
  creationTimestamp: '2024-04-05T04:45:34Z'
  generation: 1527
  labels:
    project: infrastructure
    source: external
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:chart: {}
            f:helm:
              .: {}
              f:parameters: {}
            f:repoURL: {}
            f:targetRevision: {}
          f:syncPolicy:
            .: {}
            f:syncOptions: {}
        f:status:
          .: {}
          f:controllerNamespace: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination:
                .: {}
                f:namespace: {}
                f:server: {}
              f:source:
                .: {}
                f:chart: {}
                f:helm:
                  .: {}
                  f:parameters: {}
                f:repoURL: {}
                f:targetRevision: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2024-04-05T04:45:34Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:project: {}
      manager: argocd-server
      operation: Update
      time: '2024-04-12T18:03:34Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:username: {}
              f:retry: {}
              f:sync:
                .: {}
                f:revision: {}
                f:syncOptions: {}
                f:syncStrategy:
                  .: {}
                  f:hook: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:chart: {}
                f:helm:
                  .: {}
                  f:parameters: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:images: {}
          f:sync:
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2024-04-12T18:14:31Z'
  name: redis
  namespace: argocd
  resourceVersion: '1242340'
  uid: ecd8320f-7bb2-4793-82db-fd4184ee7549
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/redis
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
    - deployStartedAt: '2024-04-03T00:34:46Z'
      deployedAt: '2024-04-03T00:34:48Z'
      id: 0
      revision: 19.0.2
      source:
        chart: redis
        helm:
          parameters:
            - name: auth.password
              value: chageme
            - name: sentinel.enabled
              value: 'true'
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 19.0.2
    - deployStartedAt: '2024-04-05T04:59:23Z'
      deployedAt: '2024-04-05T04:59:29Z'
      id: 1
      revision: 19.0.2
      source:
        chart: redis
        helm:
          parameters:
            - name: auth.password
              value: chageme
            - name: sentinel.enabled
              value: 'true'
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 19.0.2
  operationState:
    finishedAt: '2024-04-05T04:59:29Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 19.0.2
        syncOptions:
          - CreateNamespace=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: '2024-04-05T04:59:23Z'
    syncResult:
      resources:
        - group: ''
          hookPhase: Running
          kind: Namespace
          message: namespace/redis created
          name: redis
          namespace: ''
          status: Synced
          syncPhase: PreSync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: NetworkPolicy
          message: networkpolicy.networking.k8s.io/redis created
          name: redis
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ServiceAccount
          message: serviceaccount/redis created
          name: redis
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Secret
          message: secret/redis created
          name: redis
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ConfigMap
          message: configmap/redis-health created
          name: redis-health
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ConfigMap
          message: configmap/redis-configuration created
          name: redis-configuration
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ConfigMap
          message: configmap/redis-scripts created
          name: redis-scripts
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/redis-headless created
          name: redis-headless
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/redis created
          name: redis
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: StatefulSet
          message: statefulset.apps/redis-node created
          name: redis-node
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 19.0.2
      source:
        chart: redis
        helm:
          parameters:
            - name: auth.password
              value: chageme
            - name: sentinel.enabled
              value: 'true'
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 19.0.2
  reconciledAt: '2024-04-12T18:14:30Z'
  resources:
    - kind: ConfigMap
      name: redis-configuration
      namespace: redis
      status: Synced
      version: v1
    - kind: ConfigMap
      name: redis-health
      namespace: redis
      status: Synced
      version: v1
    - kind: ConfigMap
      name: redis-scripts
      namespace: redis
      status: Synced
      version: v1
    - kind: Secret
      name: redis
      namespace: redis
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: redis
      namespace: redis
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: redis-headless
      namespace: redis
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: redis
      namespace: redis
      status: Synced
      version: v1
    - group: apps
      health:
        message: >-
          statefulset rolling update complete 3 pods at revision
          redis-node-5db9569bdc...
        status: Healthy
      kind: StatefulSet
      name: redis-node
      namespace: redis
      status: Synced
      version: v1
    - group: networking.k8s.io
      kind: NetworkPolicy
      name: redis
      namespace: redis
      status: Synced
      version: v1
  sourceType: Helm
  summary:
    images:
      - docker.io/bitnami/redis-sentinel:7.2.4-debian-12-r7
      - docker.io/bitnami/redis:7.2.4-debian-12-r9
  sync:
    comparedTo:
      destination:
        namespace: redis
        server: https://kubernetes.default.svc
      source:
        chart: redis
        helm:
          parameters:
            - name: auth.password
              value: chageme
            - name: sentinel.enabled
              value: 'true'
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 19.0.2
    revision: 19.0.2
    status: Synced
spec:
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: redis
    helm:
      parameters:
        - name: auth.password
          value: chageme
        - name: sentinel.enabled
          value: 'true'
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 19.0.2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
