apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"creationTimestamp":"2024-04-03T12:53:12Z","generation":133,"labels":{"source":"internal"},"managedFields":[{"apiVersion":"argoproj.io/v1alpha1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:labels":{".":{},"f:source":{}}},"f:spec":{".":{},"f:destination":{".":{},"f:namespace":{},"f:server":{}},"f:project":{},"f:source":{".":{},"f:path":{},"f:repoURL":{},"f:targetRevision":{}},"f:syncPolicy":{".":{},"f:automated":{},"f:syncOptions":{}}},"f:status":{".":{},"f:health":{},"f:summary":{},"f:sync":{".":{},"f:comparedTo":{".":{},"f:destination":{},"f:source":{}}}}},"manager":"argocd-server","operation":"Update","time":"2024-04-03T16:15:04Z"},{"apiVersion":"argoproj.io/v1alpha1","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:controllerNamespace":{},"f:health":{"f:status":{}},"f:history":{},"f:operationState":{".":{},"f:finishedAt":{},"f:message":{},"f:operation":{".":{},"f:initiatedBy":{".":{},"f:username":{}},"f:retry":{},"f:sync":{".":{},"f:prune":{},"f:revision":{},"f:syncOptions":{},"f:syncStrategy":{".":{},"f:hook":{".":{},"f:force":{}}}}},"f:phase":{},"f:startedAt":{},"f:syncResult":{".":{},"f:resources":{},"f:revision":{},"f:source":{".":{},"f:path":{},"f:repoURL":{},"f:targetRevision":{}}}},"f:reconciledAt":{},"f:resources":{},"f:sourceType":{},"f:sync":{"f:comparedTo":{"f:destination":{"f:namespace":{},"f:server":{}},"f:source":{"f:path":{},"f:repoURL":{},"f:targetRevision":{}}},"f:revision":{},"f:status":{}}}},"manager":"argocd-application-controller","operation":"Update","time":"2024-04-03T16:15:07Z"}],"name":"secrets","namespace":"argocd","resourceVersion":"115286","selfLink":"/apis/argoproj.io/v1alpha1/namespaces/argocd/applications/secrets","uid":"2d8a986a-dc3d-4e11-af87-56f2840e6d17"},"spec":{"destination":{"namespace":"kubernetes-replicator","server":"https://kubernetes.default.svc"},"project":"infrastructure","source":{"path":"cluster/argocd/sources/secrets","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"},"syncPolicy":{"automated":{},"syncOptions":["CreateNamespace=true"]}},"status":{"controllerNamespace":"argocd","health":{"status":"Healthy"},"history":[{"deployStartedAt":"2024-04-03T12:53:16Z","deployedAt":"2024-04-03T12:53:17Z","id":0,"revision":"481139546ee797eb3b10206bc5567febfed7253f","source":{"path":"cluster/argocd/sources/secrets","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}},{"deployStartedAt":"2024-04-03T13:21:34Z","deployedAt":"2024-04-03T13:21:35Z","id":1,"revision":"728d35bf92ab4dbfb05309e21bea4f8103709d21","source":{"path":"cluster/argocd/sources/secrets","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}},{"deployStartedAt":"2024-04-03T13:21:43Z","deployedAt":"2024-04-03T13:21:44Z","id":2,"revision":"728d35bf92ab4dbfb05309e21bea4f8103709d21","source":{"path":"cluster/argocd/sources/secrets","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}},{"deployStartedAt":"2024-04-03T13:37:13Z","deployedAt":"2024-04-03T13:37:14Z","id":3,"revision":"fdc9690c8c101245583d0f6d6cc6f78b18df8872","source":{"path":"cluster/argocd/sources/secrets","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}},{"deployStartedAt":"2024-04-03T13:38:39Z","deployedAt":"2024-04-03T13:38:41Z","id":4,"revision":"fdc9690c8c101245583d0f6d6cc6f78b18df8872","source":{"path":"cluster/argocd/sources/secrets","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}},{"deployStartedAt":"2024-04-03T13:50:37Z","deployedAt":"2024-04-03T13:50:38Z","id":5,"revision":"6e5153d42634ceb039cdf145eca7b1054c2585f8","source":{"path":"cluster/argocd/sources/secrets","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}},{"deployStartedAt":"2024-04-03T16:12:09Z","deployedAt":"2024-04-03T16:12:10Z","id":6,"revision":"055ffa31724efe3651a2226d1ba1734d30fc504e","source":{"path":"cluster/argocd/sources/secrets","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}},{"deployStartedAt":"2024-04-03T16:12:55Z","deployedAt":"2024-04-03T16:12:56Z","id":7,"revision":"055ffa31724efe3651a2226d1ba1734d30fc504e","source":{"path":"cluster/argocd/sources/secrets","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}},{"deployStartedAt":"2024-04-03T16:15:04Z","deployedAt":"2024-04-03T16:15:07Z","id":8,"revision":"1a9118da6b734b1e11833a7824db22717b917425","source":{"path":"cluster/argocd/sources/secrets","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}}],"operationState":{"finishedAt":"2024-04-03T16:15:07Z","message":"successfully
      synced (all tasks
      run)","operation":{"initiatedBy":{"username":"admin"},"retry":{},"sync":{"prune":true,"revision":"1a9118da6b734b1e11833a7824db22717b917425","syncOptions":["CreateNamespace=true","Replace=true","PruneLast=true"],"syncStrategy":{"hook":{"force":true}}}},"phase":"Succeeded","startedAt":"2024-04-03T16:15:04Z","syncResult":{"resources":[{"group":"","hookPhase":"Succeeded","kind":"Secret","message":"secret
      \"secret-azure-registry\" deleted\nsecret/secret-azure-registry
      replaced","name":"secret-azure-registry","namespace":"kubernetes-replicator","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"","hookPhase":"Succeeded","kind":"Secret","message":"secret
      \"vault-token\" deleted\nsecret/vault-token
      replaced","name":"vault-token","namespace":"kubernetes-replicator","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"external-secrets.io","hookPhase":"Succeeded","kind":"ClusterSecretStore","message":"pruned","name":"vault-access-cluster-secret-store","namespace":"","status":"Pruned","syncPhase":"Sync","version":"v1beta1"},{"group":"external-secrets.io","hookPhase":"Succeeded","kind":"ClusterSecretStore","message":"pruned","name":"externalsecret-storage-connection-store","namespace":"","status":"Pruned","syncPhase":"Sync","version":"v1beta1"},{"group":"external-secrets.io","hookPhase":"Succeeded","kind":"ExternalSecret","message":"pruned","name":"vault-access-external-secret","namespace":"kubernetes-replicator","status":"Pruned","syncPhase":"Sync","version":"v1beta1"}],"revision":"1a9118da6b734b1e11833a7824db22717b917425","source":{"path":"cluster/argocd/sources/secrets","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}}},"reconciledAt":"2024-04-03T16:15:07Z","resources":[{"kind":"Secret","name":"secret-azure-registry","namespace":"kubernetes-replicator","status":"Synced","version":"v1"},{"kind":"Secret","name":"vault-token","namespace":"kubernetes-replicator","status":"Synced","version":"v1"}],"sourceType":"Kustomize","summary":{},"sync":{"comparedTo":{"destination":{"namespace":"kubernetes-replicator","server":"https://kubernetes.default.svc"},"source":{"path":"cluster/argocd/sources/secrets","repoURL":"git@github.com:Binesty/Kubernetes.git","targetRevision":"main"}},"revision":"1a9118da6b734b1e11833a7824db22717b917425","status":"Synced"}}}
  creationTimestamp: '2024-04-05T04:45:34Z'
  generation: 1338
  labels:
    project: infrastructure
    source: internal
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:path: {}
            f:repoURL: {}
            f:targetRevision: {}
          f:syncPolicy:
            .: {}
            f:syncOptions: {}
        f:status:
          .: {}
          f:controllerNamespace: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination:
                .: {}
                f:namespace: {}
                f:server: {}
              f:source:
                .: {}
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2024-04-05T04:45:34Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            f:project: {}
      manager: argocd-server
      operation: Update
      time: '2024-04-12T18:04:31Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:automated: {}
              f:retry:
                .: {}
                f:limit: {}
              f:sync:
                .: {}
                f:revision: {}
                f:syncOptions: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:sync:
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2024-04-12T18:14:32Z'
  name: secrets
  namespace: argocd
  resourceVersion: '1242353'
  uid: d7ff53c7-7728-418d-8822-56a658b63fe8
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/secrets
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
    - deployStartedAt: '2024-04-03T13:21:34Z'
      deployedAt: '2024-04-03T13:21:35Z'
      id: 1
      revision: 728d35bf92ab4dbfb05309e21bea4f8103709d21
      source:
        path: cluster/argocd/sources/secrets
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    - deployStartedAt: '2024-04-03T13:21:43Z'
      deployedAt: '2024-04-03T13:21:44Z'
      id: 2
      revision: 728d35bf92ab4dbfb05309e21bea4f8103709d21
      source:
        path: cluster/argocd/sources/secrets
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    - deployStartedAt: '2024-04-03T13:37:13Z'
      deployedAt: '2024-04-03T13:37:14Z'
      id: 3
      revision: fdc9690c8c101245583d0f6d6cc6f78b18df8872
      source:
        path: cluster/argocd/sources/secrets
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    - deployStartedAt: '2024-04-03T13:38:39Z'
      deployedAt: '2024-04-03T13:38:41Z'
      id: 4
      revision: fdc9690c8c101245583d0f6d6cc6f78b18df8872
      source:
        path: cluster/argocd/sources/secrets
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    - deployStartedAt: '2024-04-03T13:50:37Z'
      deployedAt: '2024-04-03T13:50:38Z'
      id: 5
      revision: 6e5153d42634ceb039cdf145eca7b1054c2585f8
      source:
        path: cluster/argocd/sources/secrets
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    - deployStartedAt: '2024-04-03T16:12:09Z'
      deployedAt: '2024-04-03T16:12:10Z'
      id: 6
      revision: 055ffa31724efe3651a2226d1ba1734d30fc504e
      source:
        path: cluster/argocd/sources/secrets
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    - deployStartedAt: '2024-04-03T16:12:55Z'
      deployedAt: '2024-04-03T16:12:56Z'
      id: 7
      revision: 055ffa31724efe3651a2226d1ba1734d30fc504e
      source:
        path: cluster/argocd/sources/secrets
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    - deployStartedAt: '2024-04-03T16:15:04Z'
      deployedAt: '2024-04-03T16:15:07Z'
      id: 8
      revision: 1a9118da6b734b1e11833a7824db22717b917425
      source:
        path: cluster/argocd/sources/secrets
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    - deployStartedAt: '2024-04-05T04:47:45Z'
      deployedAt: '2024-04-05T04:47:58Z'
      id: 9
      revision: 281d71653b9c9f4ba74f008d5388ee00ff481b2e
      source:
        path: cluster/argocd/sources/secrets
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    - deployStartedAt: '2024-04-10T14:11:30Z'
      deployedAt: '2024-04-10T14:11:31Z'
      id: 10
      revision: 7fc45060da8c2d88bf69b2388d7bb615deb36869
      source:
        path: cluster/argocd/sources/secrets
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
  operationState:
    finishedAt: '2024-04-10T14:11:32Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: 7fc45060da8c2d88bf69b2388d7bb615deb36869
        syncOptions:
          - CreateNamespace=true
    phase: Succeeded
    startedAt: '2024-04-10T14:11:30Z'
    syncResult:
      resources:
        - group: ''
          hookPhase: Running
          kind: Secret
          message: secret/secret-azure-registry unchanged
          name: secret-azure-registry
          namespace: kubernetes-replicator
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Secret
          message: secret/vault-token configured
          name: vault-token
          namespace: kubernetes-replicator
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 7fc45060da8c2d88bf69b2388d7bb615deb36869
      source:
        path: cluster/argocd/sources/secrets
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
  reconciledAt: '2024-04-12T18:14:30Z'
  resources:
    - kind: Secret
      name: secret-azure-registry
      namespace: kubernetes-replicator
      status: Synced
      version: v1
    - kind: Secret
      name: vault-token
      namespace: kubernetes-replicator
      status: OutOfSync
      version: v1
  sourceType: Kustomize
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: kubernetes-replicator
        server: https://kubernetes.default.svc
      source:
        path: cluster/argocd/sources/secrets
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    revision: d904e809be85b0bb64ac0d9190cda6eca26b24a4
    status: OutOfSync
spec:
  destination:
    namespace: kubernetes-replicator
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: cluster/argocd/sources/secrets
    repoURL: git@github.com:Binesty/Kubernetes.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
