apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: kafka-bridge
  namespace: kafka
spec:
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9092
  http:
    port: 8080
    # cors:
    #   allowedOrigins: "https://strimzi.io"
    #   allowedMethods: "GET,POST,PUT,DELETE,OPTIONS,PATCH"
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: bridge-ingress
#   namespace: kafka
# spec:
#   rules:
#   - host: my-bridge.io
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: kafka-bridge-bridge-service
#           servicePort: 8080