apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-access-external-secret
  namespace: workspace
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-access-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: vault-access-secret
  data:
  - secretKey: ENVIRONMENT
    remoteRef:
      key: production/vault/access
      property: ENVIRONMENT
      version: v1
  - secretKey: VAULT_ADDRESS
    remoteRef:
      key: production/vault/access
      property: VAULT_ADDRESS
      version: v1
  - secretKey: VAULT_SECRET
    remoteRef:
      key: production/vault/access
      property: VAULT_SECRET
      version: v1    
  - secretKey: VAULT_TOKEN
    remoteRef:
      key: production/vault/access
      property: VAULT_TOKEN
      version: v1