apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-access-cluster-secret-store
spec:
  provider:
    vault:
      server: "http://vault-internal.vault.svc.cluster.local:8200"
      path: "production"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---

apiVersion: v1
kind: Secret
metadata:
  name: vault-token  
data:
  token: aHZzLjZ3Z1JxbGdPajlhUVVxVmVEUVR5VDZOdg==