apiVersion: v1
kind: Secret
metadata:
  name: kafkasuper
  namespace: kafka
  labels:
    strimzi.io/kind: KafkaUser
    strimzi.io/cluster: cluster-auth
type: Opaque
data:
  password: c2VuaGFrYWZrYQo=  # senhakafka
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: kafkasuper
  namespace: kafka
  labels:
    strimzi.io/cluster: cluster-auth
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: kafkasuper
          key: password
  authorization:
    # Use the Kafka AclAuthorizer plugin
    # Options: simple, opa authorization, oauth2.0 authorization
    type: simple
    acls:
      - resource:
          type: "topic"          # topic | group | cluster | transactionalId
          name: pub            # "*" = all
          patternType: prefix  # literal | prefix
        operations:            # Read | Write | Describe | Create
          - Read
