apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: binesty-selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: "*.binesty.io"
  dnsNames:
    - "*.binesty.io"
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: binesty-ca-issuer
spec:
  ca:
    secretName: root-secret