apiVersion: v1
kind: Service
metadata:
  name: sql-server-service
  namespace: databases
spec:
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: sql-server-0
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      name: tcp