apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: binesty-selfsigned-root
  namespace: kubernetes-replicator
  labels:
    app.kubernetes.io/instance: issuers
spec:
  isCA: true
  commonName: "*.binesty.io"
  dnsNames:
    - "*.binesty.io"
  secretName: binesty-root
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to-matching: use-root-certificate=true
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---