apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: externalsecret-registry-store
  namespace: kubernetes-replicator
spec:
  provider:
    vault:
      server: "http://vault-internal.vault.svc.binesty:8200"
      path: "admin-users"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-registry
  namespace: kubernetes-replicator
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: externalsecret-registry-store
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
    name: container-registry-secret
    creationPolicy: Owner
  data:
  - secretKey: dockerconfigjson
    remoteRef:
      key: container-registry