apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: externalsecret-postgres-store
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "databases"
spec:
  provider:
    vault:
      server: "http://vault-internal.vault.svc.binesty:8200"
      path: "admin-users"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-postgres
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "databases"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: externalsecret-postgres-store
    kind: ClusterSecretStore
  target:
    name: postgres-secret
  data:  
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: databases
      property: POSTGRES_PASSWORD  
  - secretKey: POSTGRES_USER
    remoteRef:
      key: databases
      property: POSTGRES_USER