apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: externalsecret-elastic-stack-store
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "elastic-stack"
spec:
  provider:
    vault:
      server: "http://vault-internal.vault.svc.binesty:8200"
      path: "admin-users"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-elastic-stack
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "elastic-stack"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: externalsecret-elastic-stack-store
    kind: ClusterSecretStore
  target:
    name: elastic-secret
  data:  
  - secretKey: ELASTICSEARCH_HOST
    remoteRef:
      key: elastic-stack
      property: ELASTICSEARCH_HOST
  - secretKey: ELASTICSEARCH_PORT
    remoteRef:
      key: elastic-stack
      property: ELASTICSEARCH_PORT        
  - secretKey: KIBANA_HOST
    remoteRef:
      key: elastic-stack
      property: KIBANA_HOST  
  - secretKey: ELASTIC_USERNAME
    remoteRef:
      key: elastic-stack
      property: ELASTIC_USERNAME  
  - secretKey: ELASTIC_PASSWORD
    remoteRef:
      key: elastic-stack
      property: ELASTIC_PASSWORD                