apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: externalsecret-grafana-store
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "monitoring"
spec:
  provider:
    vault:
      server: "http://vault-internal.vault.svc.binesty:8200"
      path: "admin-users"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-grafana
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "monitoring"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: externalsecret-grafana-store
    kind: ClusterSecretStore
  target:
    name: monitoring-grafana
  data:  
  - secretKey: admin-password
    remoteRef:
      key: grafana
      property: admin-password  
  - secretKey: admin-user
    remoteRef:
      key: grafana
      property: admin-user   