apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: externalsecret-keycloak-store
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "keycloak"
spec:
  provider:
    vault:
      server: "http://vault-internal.vault.svc.binesty:8200"
      path: "admin-users"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-keycloak
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "keycloak"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: externalsecret-keycloak-store
    kind: ClusterSecretStore
  target:
    name: keycloak-secret
  data:  
  - secretKey: KEYCLOAK_ADMIN
    remoteRef:
      key: keycloak
      property: KEYCLOAK_ADMIN
  - secretKey: KEYCLOAK_ADMIN_PASSWORD
    remoteRef:
      key: keycloak
      property: KEYCLOAK_ADMIN_PASSWORD
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: keycloak
      property: POSTGRES_PASSWORD
  - secretKey: POSTGRES_USER
    remoteRef:
      key: keycloak
      property: POSTGRES_USER
---
