apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: externalsecret-keycloak-store
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "keycloak"
spec:
  provider:
    vault:
      server: "http://vault-internal.vault.svc.binesty:8200"
      path: "admin-users"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-keycloak
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "keycloak"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: externalsecret-keycloak-store
    kind: ClusterSecretStore
  target:
    name: keycloak-secret
  data:  
  - secretKey: admin-password
    remoteRef:
      key: keycloak
      property: admin-password  
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-keycloak-postgres
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "keycloak"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: externalsecret-keycloak-store
    kind: ClusterSecretStore
  target:
    name: keycloak-postgresql
  data:  
  - secretKey: password
    remoteRef:
      key: keycloak
      property: postgres-password
  - secretKey: database
    remoteRef:
      key: keycloak
      property: postgres-database      