apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: externalsecret-longhorn-backup-minio-store
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "longhorn-system"
spec:
  provider:
    vault:
      server: "http://vault-internal.vault.svc.binesty:8200"
      path: "admin-users"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-longhorn-backup-minio
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "longhorn-system"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: externalsecret-longhorn-backup-minio-store
    kind: ClusterSecretStore
  target:
    name: longhorn-backup-minio-secret
  data:  
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: longhorn
      property: AWS_ACCESS_KEY_ID  
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: longhorn
      property: AWS_SECRET_ACCESS_KEY
  - secretKey: AWS_ENDPOINTS
    remoteRef:
      key: longhorn
      property: AWS_ENDPOINTS      