apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: externalsecret-minio-store
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "minio"
spec:
  provider:
    vault:
      server: "http://vault-internal.vault.svc.binesty:8200"
      path: "admin-users"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-minio
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "minio"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: externalsecret-minio-store
    kind: ClusterSecretStore
  target:
    name: minio-user-secret
  data:  
  - secretKey: MINIO_ROOT_USER
    remoteRef:
      key: minio
      property: MINIO_ROOT_USER  
  - secretKey: MINIO_ROOT_PASSWORD
    remoteRef:
      key: minio
      property: MINIO_ROOT_PASSWORD        