apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: externalsecret-redis-store
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "redis"
spec:
  provider:
    vault:
      server: "http://vault-internal.vault.svc.binesty:8200"
      path: "admin-users"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externalsecret-redis
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to: "redis"
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: externalsecret-redis-store
    kind: ClusterSecretStore
  target:
    name: redis-secret
  data:  
  - secretKey: REDIS_PASSWORD
    remoteRef:
      key: redis
      property: REDIS_PASSWORD