apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: kubernetes-replicator
data:
  token: aHZzLm1Zd0p2anJpY29LSTdYNEtSSnJtWUo3ZQ==
---

apiVersion: v1
kind: Secret
metadata:
  name: secret-azure-registry
  namespace: kubernetes-replicator   
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: > 
        use-binesty-registry=true
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJiaW5lc3R5LmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJiaW5lc3R5IiwicGFzc3dvcmQiOiJhbFAzYjBKeTRXdD1SZTN1bEJ2QW1vVVI2azdUNGlycCIsImF1dGgiOiJZbWx1WlhOMGVUcGhiRkF6WWpCS2VUUlhkRDFTWlROMWJFSjJRVzF2VlZJMmF6ZFVOR2x5Y0E9PSJ9fX0=
type: kubernetes.io/dockerconfigjson
---