apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2023-08-10T21:57:29Z'
  generation: 1322
  labels:
    source: external
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:username: {}
              f:retry: {}
              f:sync:
                .: {}
                f:revision: {}
                f:syncOptions: {}
                f:syncStrategy:
                  .: {}
                  f:hook: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:chart: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:images: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:chart: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2023-08-18T00:04:17Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:chart: {}
            f:repoURL: {}
            f:targetRevision: {}
          f:syncPolicy:
            .: {}
            f:syncOptions: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2023-08-18T00:05:07Z'
  name: kubernetes-replicator
  namespace: argocd
  resourceVersion: '7396786'
  uid: e2171c86-75e3-4884-9b12-47c2b2442cd2
  selfLink: >-
    /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/kubernetes-replicator
status:
  health:
    status: Healthy
  history:
    - deployStartedAt: '2023-08-10T21:57:44Z'
      deployedAt: '2023-08-10T21:57:48Z'
      id: 0
      revision: 2.9.1
      source:
        chart: kubernetes-replicator
        repoURL: https://helm.mittwald.de
        targetRevision: 2.9.1
  operationState:
    finishedAt: '2023-08-10T21:57:48Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 2.9.1
        syncOptions:
          - CreateNamespace=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: '2023-08-10T21:57:44Z'
    syncResult:
      resources:
        - group: ''
          hookPhase: Running
          kind: Namespace
          message: namespace/kubernetes-replicator created
          name: kubernetes-replicator
          namespace: ''
          status: Synced
          syncPhase: PreSync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ServiceAccount
          message: serviceaccount/kubernetes-replicator created
          name: kubernetes-replicator
          namespace: kubernetes-replicator
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: ClusterRole
          message: "clusterrole.rbac.authorization.k8s.io/kubernetes-replicator reconciled. reconciliation required create\n\tmissing rules added:\n\t\t{Verbs:[get watch list] APIGroups:[] Resources:[namespaces] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get watch list create update patch delete] APIGroups:[] Resources:[secrets configmaps serviceaccounts] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get watch list create update patch delete] APIGroups:[rbac.authorization.k8s.io] Resources:[roles rolebindings] ResourceNames:[] NonResourceURLs:[]}. clusterrole.rbac.authorization.k8s.io/kubernetes-replicator configured. Warning: resource clusterroles/kubernetes-replicator is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by  apply.  apply should only be used on resources created declaratively by either  create --save-config or  apply. The missing annotation will be patched automatically."
          name: kubernetes-replicator
          namespace: kubernetes-replicator
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: ClusterRoleBinding
          message: "clusterrolebinding.rbac.authorization.k8s.io/kubernetes-replicator reconciled. reconciliation required create\n\tmissing subjects added:\n\t\t{Kind:ServiceAccount APIGroup: Name:kubernetes-replicator Namespace:kubernetes-replicator}. clusterrolebinding.rbac.authorization.k8s.io/kubernetes-replicator configured. Warning: resource clusterrolebindings/kubernetes-replicator is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by  apply.  apply should only be used on resources created declaratively by either  create --save-config or  apply. The missing annotation will be patched automatically."
          name: kubernetes-replicator
          namespace: kubernetes-replicator
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: Deployment
          message: deployment.apps/kubernetes-replicator created
          name: kubernetes-replicator
          namespace: kubernetes-replicator
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 2.9.1
      source:
        chart: kubernetes-replicator
        repoURL: https://helm.mittwald.de
        targetRevision: 2.9.1
  reconciledAt: '2023-08-18T00:04:17Z'
  resources:
    - kind: ServiceAccount
      name: kubernetes-replicator
      namespace: kubernetes-replicator
      status: Synced
      version: v1
    - group: apps
      health:
        status: Healthy
      kind: Deployment
      name: kubernetes-replicator
      namespace: kubernetes-replicator
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: kubernetes-replicator
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: kubernetes-replicator
      status: Synced
      version: v1
  sourceType: Helm
  summary:
    images:
      - quay.io/mittwald/kubernetes-replicator:v2.9.1
  sync:
    comparedTo:
      destination:
        namespace: kubernetes-replicator
        server: https://kubernetes.default.svc
      source:
        chart: kubernetes-replicator
        repoURL: https://helm.mittwald.de
        targetRevision: 2.9.1
    revision: 2.9.1
    status: Synced
spec:
  destination:
    namespace: kubernetes-replicator
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: kubernetes-replicator
    repoURL: https://helm.mittwald.de
    targetRevision: 2.9.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
