apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2023-08-22T13:36:46Z'
  generation: 4427
  labels:
    source: internal
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:path: {}
            f:repoURL: {}
            f:targetRevision: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2023-08-22T13:37:35Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:controllerNamespace: {}
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:username: {}
              f:retry: {}
              f:sync:
                .: {}
                f:prune: {}
                f:revision: {}
                f:syncOptions: {}
                f:syncStrategy:
                  .: {}
                  f:hook: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:images: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2023-09-28T18:48:45Z'
  name: metrics-server
  namespace: argocd
  resourceVersion: '12045272'
  uid: 2821eecd-a16f-4efc-acfa-ac22d832decd
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/metrics-server
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
    - deployStartedAt: '2023-08-22T13:37:05Z'
      deployedAt: '2023-08-22T13:37:07Z'
      id: 0
      revision: f6512de4b9852b877fff6fc4444d4487e031a9d2
      source:
        path: metrics-server
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
  operationState:
    finishedAt: '2023-08-22T13:37:07Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        prune: true
        revision: f6512de4b9852b877fff6fc4444d4487e031a9d2
        syncOptions:
          - PruneLast=true
          - Replace=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: '2023-08-22T13:37:05Z'
    syncResult:
      resources:
        - group: ''
          hookPhase: Running
          kind: ServiceAccount
          message: serviceaccount/metrics-server replaced
          name: metrics-server
          namespace: kube-system
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: ClusterRole
          message: >-
            clusterrole.rbac.authorization.k8s.io/system:metrics-server
            reconciled. reconciliation required update.
            clusterrole.rbac.authorization.k8s.io/system:metrics-server replaced
          name: system:metrics-server
          namespace: kube-system
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: ClusterRole
          message: >-
            clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader
            reconciled. reconciliation required update.
            clusterrole.rbac.authorization.k8s.io/system:aggregated-metrics-reader
            replaced
          name: system:aggregated-metrics-reader
          namespace: kube-system
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: ClusterRoleBinding
          message: >-
            clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator
            reconciled. reconciliation required update.
            clusterrolebinding.rbac.authorization.k8s.io/metrics-server:system:auth-delegator
            replaced
          name: metrics-server:system:auth-delegator
          namespace: kube-system
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: ClusterRoleBinding
          message: >-
            clusterrolebinding.rbac.authorization.k8s.io/system:metrics-server
            reconciled. reconciliation required update.
            clusterrolebinding.rbac.authorization.k8s.io/system:metrics-server
            replaced
          name: system:metrics-server
          namespace: kube-system
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: RoleBinding
          message: >-
            rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader
            reconciled. reconciliation required update.
            rolebinding.rbac.authorization.k8s.io/metrics-server-auth-reader
            replaced
          name: metrics-server-auth-reader
          namespace: kube-system
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/metrics-server replaced
          name: metrics-server
          namespace: kube-system
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: Deployment
          message: deployment.apps/metrics-server replaced
          name: metrics-server
          namespace: kube-system
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apiregistration.k8s.io
          hookPhase: Running
          kind: APIService
          message: apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io replaced
          name: v1beta1.metrics.k8s.io
          namespace: kube-system
          status: Synced
          syncPhase: Sync
          version: v1
      revision: f6512de4b9852b877fff6fc4444d4487e031a9d2
      source:
        path: metrics-server
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
  reconciledAt: '2023-09-28T18:48:45Z'
  resources:
    - health:
        status: Healthy
      kind: Service
      name: metrics-server
      namespace: kube-system
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: metrics-server
      namespace: kube-system
      status: Synced
      version: v1
    - group: apiregistration.k8s.io
      health:
        message: 'Passed: all checks passed'
        status: Healthy
      kind: APIService
      name: v1beta1.metrics.k8s.io
      status: Synced
      version: v1
    - group: apps
      health:
        status: Healthy
      kind: Deployment
      name: metrics-server
      namespace: kube-system
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:aggregated-metrics-reader
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:metrics-server
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: metrics-server:system:auth-delegator
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: system:metrics-server
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: metrics-server-auth-reader
      namespace: kube-system
      status: Synced
      version: v1
  sourceType: Directory
  summary:
    images:
      - registry.k8s.io/metrics-server/metrics-server:v0.6.4
  sync:
    comparedTo:
      destination:
        namespace: kube-system
        server: https://kubernetes.default.svc
      source:
        path: metrics-server
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
    revision: 932644b53ec22ca93728f01328cf363526eb5245
    status: Synced
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: metrics-server
    repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
    targetRevision: HEAD
