apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2023-07-11T18:18:12Z'
  generation: 7009
  labels:
    source: external
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:chart: {}
            f:helm:
              .: {}
              f:parameters: {}
            f:repoURL: {}
            f:targetRevision: {}
          f:syncPolicy:
            .: {}
            f:syncOptions: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2023-08-16T14:24:44Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:username: {}
              f:retry: {}
              f:sync:
                .: {}
                f:prune: {}
                f:revision: {}
                f:syncOptions: {}
                f:syncStrategy:
                  .: {}
                  f:hook:
                    .: {}
                    f:force: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:chart: {}
                f:helm:
                  .: {}
                  f:parameters: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:externalURLs: {}
            f:images: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:chart: {}
                f:helm:
                  .: {}
                  f:parameters: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2023-08-16T14:36:47Z'
  name: rabbitmq
  namespace: argocd
  resourceVersion: '7078814'
  uid: 4ad28479-17f6-41fa-a3fa-bd3ae25ea335
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/rabbitmq
status:
  health:
    status: Healthy
  history:
    - deployStartedAt: '2023-07-11T18:19:02Z'
      deployedAt: '2023-07-11T18:19:14Z'
      id: 0
      revision: 12.0.4
      source:
        chart: rabbitmq
        helm:
          parameters:
            - name: auth.password
              value: user
            - name: replicaCount
              value: '3'
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 12.0.4
    - deployStartedAt: '2023-08-16T14:20:07Z'
      deployedAt: '2023-08-16T14:20:09Z'
      id: 1
      revision: 12.0.10
      source:
        chart: rabbitmq
        helm:
          parameters:
            - name: auth.password
              value: user
            - name: replicaCount
              value: '3'
            - name: ingress.enabled
              value: 'true'
            - name: ingress.hostname
              value: rabbitmq.binesty.net
            - name: ingress.ingressClassName
              value: nginx
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 12.0.10
    - deployStartedAt: '2023-08-16T14:24:44Z'
      deployedAt: '2023-08-16T14:24:46Z'
      id: 2
      revision: 12.0.10
      source:
        chart: rabbitmq
        helm:
          parameters:
            - name: auth.password
              value: user
            - name: replicaCount
              value: '3'
            - name: ingress.enabled
              value: 'true'
            - name: ingress.hostname
              value: rabbitmq.binesty.net
            - name: ingress.ingressClassName
              value: nginx
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 12.0.10
  operationState:
    finishedAt: '2023-08-16T14:24:46Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        prune: true
        revision: 12.0.10
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Replace=true
        syncStrategy:
          hook:
            force: true
    phase: Succeeded
    startedAt: '2023-08-16T14:24:44Z'
    syncResult:
      resources:
        - group: ''
          hookPhase: Running
          kind: ServiceAccount
          message: |-
            serviceaccount "rabbitmq" deleted
            serviceaccount/rabbitmq replaced
          name: rabbitmq
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Secret
          message: |-
            secret "rabbitmq-config" deleted
            secret/rabbitmq-config replaced
          name: rabbitmq-config
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Secret
          message: |-
            secret "rabbitmq" deleted
            secret/rabbitmq replaced
          name: rabbitmq
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: Role
          message: >-
            role.rbac.authorization.k8s.io/rabbitmq-endpoint-reader reconciled.
            role.rbac.authorization.k8s.io "rabbitmq-endpoint-reader" deleted

            role.rbac.authorization.k8s.io/rabbitmq-endpoint-reader replaced
          name: rabbitmq-endpoint-reader
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: RoleBinding
          message: >-
            rolebinding.rbac.authorization.k8s.io/rabbitmq-endpoint-reader
            reconciled. rolebinding.rbac.authorization.k8s.io
            "rabbitmq-endpoint-reader" deleted

            rolebinding.rbac.authorization.k8s.io/rabbitmq-endpoint-reader
            replaced
          name: rabbitmq-endpoint-reader
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: |-
            service "rabbitmq-headless" deleted
            service/rabbitmq-headless replaced
          name: rabbitmq-headless
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: |-
            service "rabbitmq" deleted
            service/rabbitmq replaced
          name: rabbitmq
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: StatefulSet
          message: |-
            statefulset.apps "rabbitmq" deleted
            statefulset.apps/rabbitmq replaced
          name: rabbitmq
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: Ingress
          message: |-
            ingress.networking.k8s.io "rabbitmq" deleted
            ingress.networking.k8s.io/rabbitmq replaced
          name: rabbitmq
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 12.0.10
      source:
        chart: rabbitmq
        helm:
          parameters:
            - name: auth.password
              value: user
            - name: replicaCount
              value: '3'
            - name: ingress.enabled
              value: 'true'
            - name: ingress.hostname
              value: rabbitmq.binesty.net
            - name: ingress.ingressClassName
              value: nginx
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 12.0.10
  reconciledAt: '2023-08-16T14:36:46Z'
  resources:
    - kind: Secret
      name: rabbitmq
      namespace: rabbitmq
      status: Synced
      version: v1
    - kind: Secret
      name: rabbitmq-config
      namespace: rabbitmq
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: rabbitmq
      namespace: rabbitmq
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: rabbitmq-headless
      namespace: rabbitmq
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: rabbitmq
      namespace: rabbitmq
      status: Synced
      version: v1
    - group: apps
      health:
        message: >-
          statefulset rolling update complete 3 pods at revision
          rabbitmq-64fbb77cc6...
        status: Healthy
      kind: StatefulSet
      name: rabbitmq
      namespace: rabbitmq
      status: Synced
      version: v1
    - group: networking.k8s.io
      health:
        status: Healthy
      kind: Ingress
      name: rabbitmq
      namespace: rabbitmq
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: Role
      name: rabbitmq-endpoint-reader
      namespace: rabbitmq
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: rabbitmq-endpoint-reader
      namespace: rabbitmq
      status: Synced
      version: v1
  sourceType: Helm
  summary:
    externalURLs:
      - http://rabbitmq.binesty.net/
    images:
      - docker.io/bitnami/rabbitmq:3.12.2-debian-11-r8
  sync:
    comparedTo:
      destination:
        namespace: rabbitmq
        server: https://kubernetes.default.svc
      source:
        chart: rabbitmq
        helm:
          parameters:
            - name: auth.password
              value: user
            - name: replicaCount
              value: '3'
            - name: ingress.enabled
              value: 'true'
            - name: ingress.hostname
              value: rabbitmq.binesty.net
            - name: ingress.ingressClassName
              value: nginx
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 12.0.10
    revision: 12.0.10
    status: Synced
spec:
  destination:
    namespace: rabbitmq
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: rabbitmq
    helm:
      parameters:
        - name: auth.password
          value: user
        - name: replicaCount
          value: '3'
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hostname
          value: rabbitmq.binesty.net
        - name: ingress.ingressClassName
          value: nginx
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.0.10
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
