apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2023-08-17T23:34:36Z'
  generation: 5909
  labels:
    source: external
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:chart: {}
            f:repoURL: {}
            f:targetRevision: {}
          f:syncPolicy:
            .: {}
            f:syncOptions: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2023-09-14T21:27:29Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:controllerNamespace: {}
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:username: {}
              f:retry: {}
              f:sync:
                .: {}
                f:prune: {}
                f:revision: {}
                f:syncOptions: {}
                f:syncStrategy:
                  .: {}
                  f:hook:
                    .: {}
                    f:force: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:chart: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:images: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:chart: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2023-09-28T18:51:45Z'
  name: redis
  namespace: argocd
  resourceVersion: '12046105'
  uid: c2589f2e-237d-442b-808e-51d2fb60b7ad
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/redis
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
    - deployStartedAt: '2023-08-17T23:34:54Z'
      deployedAt: '2023-08-17T23:34:59Z'
      id: 0
      revision: 17.15.5
      source:
        chart: redis
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 17.15.5
    - deployStartedAt: '2023-08-23T23:50:15Z'
      deployedAt: '2023-08-23T23:50:17Z'
      id: 1
      revision: 17.15.5
      source:
        chart: redis
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 17.15.5
    - deployStartedAt: '2023-08-24T00:32:49Z'
      deployedAt: '2023-08-24T00:33:02Z'
      id: 2
      revision: 17.15.5
      source:
        chart: redis
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 17.15.5
    - deployStartedAt: '2023-08-24T01:00:26Z'
      deployedAt: '2023-08-24T01:00:38Z'
      id: 3
      revision: 17.16.0
      source:
        chart: redis
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 17.16.0
    - deployStartedAt: '2023-08-24T01:35:37Z'
      deployedAt: '2023-08-24T01:35:50Z'
      id: 4
      revision: 17.16.0
      source:
        chart: redis
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 17.16.0
    - deployStartedAt: '2023-09-14T21:27:29Z'
      deployedAt: '2023-09-14T21:27:31Z'
      id: 5
      revision: 18.0.4
      source:
        chart: redis
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 18.0.4
  operationState:
    finishedAt: '2023-09-14T21:27:31Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        prune: true
        revision: 18.0.4
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Replace=true
        syncStrategy:
          hook:
            force: true
    phase: Succeeded
    startedAt: '2023-09-14T21:27:29Z'
    syncResult:
      resources:
        - group: ''
          hookPhase: Running
          kind: ServiceAccount
          message: |-
            serviceaccount "redis" deleted
            serviceaccount/redis replaced
          name: redis
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Secret
          message: |-
            secret "redis" deleted
            secret/redis replaced
          name: redis
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ConfigMap
          message: |-
            configmap "redis-health" deleted
            configmap/redis-health replaced
          name: redis-health
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ConfigMap
          message: |-
            configmap "redis-scripts" deleted
            configmap/redis-scripts replaced
          name: redis-scripts
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ConfigMap
          message: |-
            configmap "redis-configuration" deleted
            configmap/redis-configuration replaced
          name: redis-configuration
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: |-
            service "redis-replicas" deleted
            service/redis-replicas replaced
          name: redis-replicas
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: |-
            service "redis-headless" deleted
            service/redis-headless replaced
          name: redis-headless
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: |-
            service "redis-master" deleted
            service/redis-master replaced
          name: redis-master
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: StatefulSet
          message: |-
            statefulset.apps "redis-master" deleted
            statefulset.apps/redis-master replaced
          name: redis-master
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: StatefulSet
          message: |-
            statefulset.apps "redis-replicas" deleted
            statefulset.apps/redis-replicas replaced
          name: redis-replicas
          namespace: redis
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 18.0.4
      source:
        chart: redis
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 18.0.4
  reconciledAt: '2023-09-28T18:51:45Z'
  resources:
    - kind: ConfigMap
      name: redis-configuration
      namespace: redis
      status: Synced
      version: v1
    - kind: ConfigMap
      name: redis-health
      namespace: redis
      status: Synced
      version: v1
    - kind: ConfigMap
      name: redis-scripts
      namespace: redis
      status: Synced
      version: v1
    - kind: Secret
      name: redis
      namespace: redis
      status: OutOfSync
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: redis-headless
      namespace: redis
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: redis-master
      namespace: redis
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: redis-replicas
      namespace: redis
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: redis
      namespace: redis
      status: Synced
      version: v1
    - group: apps
      health:
        message: >-
          statefulset rolling update complete 1 pods at revision
          redis-master-5d8c69f69f...
        status: Healthy
      kind: StatefulSet
      name: redis-master
      namespace: redis
      status: OutOfSync
      version: v1
    - group: apps
      health:
        message: >-
          statefulset rolling update complete 3 pods at revision
          redis-replicas-78cb75657c...
        status: Healthy
      kind: StatefulSet
      name: redis-replicas
      namespace: redis
      status: OutOfSync
      version: v1
  sourceType: Helm
  summary:
    images:
      - docker.io/bitnami/redis:7.2.1-debian-11-r0
  sync:
    comparedTo:
      destination:
        namespace: redis
        server: https://kubernetes.default.svc
      source:
        chart: redis
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 18.0.4
    revision: 18.0.4
    status: OutOfSync
spec:
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 18.0.4
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
