apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2023-09-11T20:58:22Z'
  generation: 1070
  labels:
    source: external
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:chart: {}
            f:repoURL: {}
            f:targetRevision: {}
          f:syncPolicy:
            .: {}
            f:syncOptions: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2023-09-12T12:27:49Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:controllerNamespace: {}
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:username: {}
              f:retry: {}
              f:sync:
                .: {}
                f:revision: {}
                f:syncOptions: {}
                f:syncStrategy:
                  .: {}
                  f:hook: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:chart: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:images: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:chart: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2023-09-28T18:51:45Z'
  name: traces
  namespace: argocd
  resourceVersion: '12046098'
  uid: 85c4cff4-1e59-4e66-b88d-83a082543d71
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/traces
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
    - deployStartedAt: '2023-09-11T20:58:53Z'
      deployedAt: '2023-09-11T20:58:58Z'
      id: 0
      revision: 1.6.1
      source:
        chart: tempo
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: 1.6.1
  operationState:
    finishedAt: '2023-09-11T20:58:58Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 1.6.1
        syncOptions:
          - CreateNamespace=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: '2023-09-11T20:58:53Z'
    syncResult:
      resources:
        - group: ''
          hookPhase: Running
          kind: Namespace
          message: namespace/traces created
          name: traces
          namespace: ''
          status: Synced
          syncPhase: PreSync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ServiceAccount
          message: serviceaccount/traces-tempo created
          name: traces-tempo
          namespace: traces
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ConfigMap
          message: configmap/tempo created
          name: tempo
          namespace: traces
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/traces-tempo created
          name: traces-tempo
          namespace: traces
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: StatefulSet
          message: statefulset.apps/traces-tempo created
          name: traces-tempo
          namespace: traces
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 1.6.1
      source:
        chart: tempo
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: 1.6.1
  reconciledAt: '2023-09-28T18:51:45Z'
  resources:
    - kind: ConfigMap
      name: tempo
      namespace: traces
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: traces-tempo
      namespace: traces
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: traces-tempo
      namespace: traces
      status: Synced
      version: v1
    - group: apps
      health:
        message: >-
          statefulset rolling update complete 1 pods at revision
          traces-tempo-97d7ff855...
        status: Healthy
      kind: StatefulSet
      name: traces-tempo
      namespace: traces
      status: Synced
      version: v1
  sourceType: Helm
  summary:
    images:
      - grafana/tempo:2.2.2
  sync:
    comparedTo:
      destination:
        namespace: traces
        server: https://kubernetes.default.svc
      source:
        chart: tempo
        repoURL: https://grafana.github.io/helm-charts
        targetRevision: 1.6.1
    revision: 1.6.1
    status: Synced
spec:
  destination:
    namespace: traces
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: tempo
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.6.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
