apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:  
  generation: 2
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      manager: argocd-server
  name: applications
  namespace: argocd
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/appprojects/default
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'