apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2023-06-28T22:56:00Z'
  generation: 502
  labels:
    source: internal
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:path: {}
            f:repoURL: {}
            f:targetRevision: {}
          f:syncPolicy:
            .: {}
            f:automated: {}
            f:syncOptions: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2023-06-29T17:23:11Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:username: {}
              f:retry: {}
              f:sync:
                .: {}
                f:prune: {}
                f:revision: {}
                f:syncOptions: {}
                f:syncStrategy:
                  .: {}
                  f:hook:
                    .: {}
                    f:force: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:externalURLs: {}
            f:images: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2023-06-29T23:27:52Z'
  name: elastic-stack
  namespace: argocd
  resourceVersion: '16370773'
  uid: ad211912-e012-45e4-8d17-c534c69de1fa
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/elastic-stack
status:
  health:
    status: Healthy
  history:
    - deployStartedAt: '2023-06-28T23:00:57Z'
      deployedAt: '2023-06-28T23:00:58Z'
      id: 0
      revision: d1498fbbe7e5cde593b8f9345a3724b849aa0121
      source:
        path: elastic
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
    - deployStartedAt: '2023-06-28T23:08:19Z'
      deployedAt: '2023-06-28T23:08:22Z'
      id: 1
      revision: d1498fbbe7e5cde593b8f9345a3724b849aa0121
      source:
        path: elastic
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
    - deployStartedAt: '2023-06-29T14:58:40Z'
      deployedAt: '2023-06-29T14:58:42Z'
      id: 2
      revision: 6cca8db8c8c17e61fa0a21df3f74c302831dff58
      source:
        path: elastic
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
    - deployStartedAt: '2023-06-29T17:14:21Z'
      deployedAt: '2023-06-29T17:14:22Z'
      id: 3
      revision: 74c1c9e877e4a388185c3e19ffc4ceb4161ba3ed
      source:
        path: elastic
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
    - deployStartedAt: '2023-06-29T17:23:11Z'
      deployedAt: '2023-06-29T17:23:15Z'
      id: 4
      revision: 74c1c9e877e4a388185c3e19ffc4ceb4161ba3ed
      source:
        path: elastic
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
  operationState:
    finishedAt: '2023-06-29T17:23:15Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        prune: true
        revision: 74c1c9e877e4a388185c3e19ffc4ceb4161ba3ed
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
        syncStrategy:
          hook:
            force: true
    phase: Succeeded
    startedAt: '2023-06-29T17:23:11Z'
    syncResult:
      resources:
        - group: ''
          hookPhase: Running
          kind: Namespace
          message: namespace/elastic-stack created
          name: elastic-stack
          namespace: ''
          status: Synced
          syncPhase: PreSync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Secret
          message: secret/elastic-secret created
          name: elastic-secret
          namespace: elastic-stack
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ConfigMap
          message: configmap/apm-server-config created
          name: apm-server-config
          namespace: elastic-stack
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ConfigMap
          message: configmap/logstash-configmap created
          name: logstash-configmap
          namespace: elastic-stack
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/apm-server created
          name: apm-server
          namespace: elastic-stack
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/elasticsearch created
          name: elasticsearch
          namespace: elastic-stack
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/logstash-service created
          name: logstash-service
          namespace: elastic-stack
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/kibana-service created
          name: kibana-service
          namespace: elastic-stack
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: Deployment
          message: deployment.apps/logstash created
          name: logstash
          namespace: elastic-stack
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: Deployment
          message: deployment.apps/kibana created
          name: kibana
          namespace: elastic-stack
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: StatefulSet
          message: statefulset.apps/apm-server created
          name: apm-server
          namespace: elastic-stack
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: StatefulSet
          message: statefulset.apps/elasticsearch-cluster created
          name: elasticsearch-cluster
          namespace: elastic-stack
          status: Synced
          syncPhase: Sync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: Ingress
          message: ingress.networking.k8s.io/apm-ingress created
          name: apm-ingress
          namespace: elastic-stack
          status: Synced
          syncPhase: Sync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: Ingress
          message: ingress.networking.k8s.io/elasticsearch-ingress created
          name: elasticsearch-ingress
          namespace: elastic-stack
          status: Synced
          syncPhase: Sync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: Ingress
          message: ingress.networking.k8s.io/kibana-ingress created
          name: kibana-ingress
          namespace: elastic-stack
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 74c1c9e877e4a388185c3e19ffc4ceb4161ba3ed
      source:
        path: elastic
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
  reconciledAt: '2023-06-29T23:27:52Z'
  resources:
    - kind: ConfigMap
      name: apm-server-config
      namespace: elastic-stack
      status: Synced
      version: v1
    - kind: ConfigMap
      name: logstash-configmap
      namespace: elastic-stack
      status: Synced
      version: v1
    - kind: Secret
      name: elastic-secret
      namespace: elastic-stack
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: apm-server
      namespace: elastic-stack
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: elasticsearch
      namespace: elastic-stack
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: kibana-service
      namespace: elastic-stack
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: logstash-service
      namespace: elastic-stack
      status: Synced
      version: v1
    - group: apps
      health:
        status: Healthy
      kind: Deployment
      name: kibana
      namespace: elastic-stack
      status: Synced
      version: v1
    - group: apps
      health:
        status: Healthy
      kind: Deployment
      name: logstash
      namespace: elastic-stack
      status: Synced
      version: v1
    - group: apps
      health:
        message: 'partitioned roll out complete: 1 new pods have been updated...'
        status: Healthy
      kind: StatefulSet
      name: apm-server
      namespace: elastic-stack
      status: Synced
      version: v1
    - group: apps
      health:
        message: 'partitioned roll out complete: 1 new pods have been updated...'
        status: Healthy
      kind: StatefulSet
      name: elasticsearch-cluster
      namespace: elastic-stack
      status: Synced
      version: v1
    - group: networking.k8s.io
      health:
        status: Healthy
      kind: Ingress
      name: apm-ingress
      namespace: elastic-stack
      status: Synced
      version: v1
    - group: networking.k8s.io
      health:
        status: Healthy
      kind: Ingress
      name: elasticsearch-ingress
      namespace: elastic-stack
      status: Synced
      version: v1
    - group: networking.k8s.io
      health:
        status: Healthy
      kind: Ingress
      name: kibana-ingress
      namespace: elastic-stack
      status: Synced
      version: v1
  sourceType: Kustomize
  summary:
    externalURLs:
      - http://apm.binesty.net/
      - http://elasticsearch.binesty.net/
      - http://kibana.binesty.net/
    images:
      - busybox
      - docker.elastic.co/apm/apm-server:7.17.9
      - docker.elastic.co/elasticsearch/elasticsearch:7.17.9
      - docker.elastic.co/kibana/kibana:7.17.9
      - docker.elastic.co/logstash/logstash:7.17.9
  sync:
    comparedTo:
      destination:
        namespace: elastic-stack
        server: https://kubernetes.default.svc
      source:
        path: elastic
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
    revision: 74c1c9e877e4a388185c3e19ffc4ceb4161ba3ed
    status: Synced
spec:
  destination:
    namespace: elastic-stack
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: elastic
    repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
