apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2023-07-06T12:36:04Z'
  generation: 5598
  labels:
    source: external
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:chart: {}
            f:helm:
              .: {}
              f:parameters: {}
            f:repoURL: {}
            f:targetRevision: {}
          f:syncPolicy:
            .: {}
            f:syncOptions: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2023-07-06T12:36:33Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:username: {}
              f:retry: {}
              f:sync:
                .: {}
                f:revision: {}
                f:syncOptions: {}
                f:syncStrategy:
                  .: {}
                  f:hook: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:chart: {}
                f:helm:
                  .: {}
                  f:parameters: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:images: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:chart: {}
                f:helm:
                  .: {}
                  f:parameters: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2023-08-03T20:28:40Z'
  name: ingress-nginx
  namespace: argocd
  resourceVersion: '4519018'
  uid: 13d0c773-63ae-4645-904f-9ebb48b355bf
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/ingress-nginx
status:
  health:
    status: Healthy
  history:
    - deployStartedAt: '2023-07-06T12:36:33Z'
      deployedAt: '2023-07-06T12:36:35Z'
      id: 0
      revision: 4.7.1
      source:
        chart: ingress-nginx
        helm:
          parameters:
            - name: controller.admissionWebhooks.enabled
              value: 'false'
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: 4.7.1
  operationState:
    finishedAt: '2023-07-06T12:36:35Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        revision: 4.7.1
        syncOptions:
          - CreateNamespace=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: '2023-07-06T12:36:33Z'
    syncResult:
      resources:
        - group: ''
          hookPhase: Running
          kind: ServiceAccount
          message: serviceaccount/ingress-nginx created
          name: ingress-nginx
          namespace: ingress-nginx
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ConfigMap
          message: configmap/ingress-nginx-controller created
          name: ingress-nginx-controller
          namespace: ingress-nginx
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: ClusterRole
          message: "clusterrole.rbac.authorization.k8s.io/ingress-nginx reconciled. reconciliation required create\n\tmissing rules added:\n\t\t{Verbs:[list watch] APIGroups:[] Resources:[configmaps endpoints nodes pods secrets namespaces] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[list watch] APIGroups:[coordination.k8s.io] Resources:[leases] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get] APIGroups:[] Resources:[nodes] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get list watch] APIGroups:[] Resources:[services] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get list watch] APIGroups:[networking.k8s.io] Resources:[ingresses] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[create patch] APIGroups:[] Resources:[events] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[update] APIGroups:[networking.k8s.io] Resources:[ingresses/status] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get list watch] APIGroups:[networking.k8s.io] Resources:[ingressclasses] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[list watch get] APIGroups:[discovery.k8s.io] Resources:[endpointslices] ResourceNames:[] NonResourceURLs:[]}. clusterrole.rbac.authorization.k8s.io/ingress-nginx configured. Warning: resource clusterroles/ingress-nginx is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by  apply.  apply should only be used on resources created declaratively by either  create --save-config or  apply. The missing annotation will be patched automatically."
          name: ingress-nginx
          namespace: ingress-nginx
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: ClusterRoleBinding
          message: "clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx reconciled. reconciliation required create\n\tmissing subjects added:\n\t\t{Kind:ServiceAccount APIGroup: Name:ingress-nginx Namespace:ingress-nginx}. clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx configured. Warning: resource clusterrolebindings/ingress-nginx is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by  apply.  apply should only be used on resources created declaratively by either  create --save-config or  apply. The missing annotation will be patched automatically."
          name: ingress-nginx
          namespace: ingress-nginx
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: Role
          message: "role.rbac.authorization.k8s.io/ingress-nginx reconciled. reconciliation required create\n\tmissing rules added:\n\t\t{Verbs:[get] APIGroups:[] Resources:[namespaces] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get list watch] APIGroups:[] Resources:[configmaps pods secrets endpoints] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get list watch] APIGroups:[] Resources:[services] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get list watch] APIGroups:[networking.k8s.io] Resources:[ingresses] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[update] APIGroups:[networking.k8s.io] Resources:[ingresses/status] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get list watch] APIGroups:[networking.k8s.io] Resources:[ingressclasses] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[get update] APIGroups:[coordination.k8s.io] Resources:[leases] ResourceNames:[ingress-nginx-leader] NonResourceURLs:[]}\n\t\t{Verbs:[create] APIGroups:[coordination.k8s.io] Resources:[leases] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[create patch] APIGroups:[] Resources:[events] ResourceNames:[] NonResourceURLs:[]}\n\t\t{Verbs:[list watch get] APIGroups:[discovery.k8s.io] Resources:[endpointslices] ResourceNames:[] NonResourceURLs:[]}. role.rbac.authorization.k8s.io/ingress-nginx configured. Warning: resource roles/ingress-nginx is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by  apply.  apply should only be used on resources created declaratively by either  create --save-config or  apply. The missing annotation will be patched automatically."
          name: ingress-nginx
          namespace: ingress-nginx
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: RoleBinding
          message: "rolebinding.rbac.authorization.k8s.io/ingress-nginx reconciled. reconciliation required create\n\tmissing subjects added:\n\t\t{Kind:ServiceAccount APIGroup: Name:ingress-nginx Namespace:ingress-nginx}. rolebinding.rbac.authorization.k8s.io/ingress-nginx configured. Warning: resource rolebindings/ingress-nginx is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by  apply.  apply should only be used on resources created declaratively by either  create --save-config or  apply. The missing annotation will be patched automatically."
          name: ingress-nginx
          namespace: ingress-nginx
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/ingress-nginx-controller created
          name: ingress-nginx-controller
          namespace: ingress-nginx
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: Deployment
          message: deployment.apps/ingress-nginx-controller created
          name: ingress-nginx-controller
          namespace: ingress-nginx
          status: Synced
          syncPhase: Sync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: IngressClass
          message: ingressclass.networking.k8s.io/nginx created
          name: nginx
          namespace: ingress-nginx
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 4.7.1
      source:
        chart: ingress-nginx
        helm:
          parameters:
            - name: controller.admissionWebhooks.enabled
              value: 'false'
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: 4.7.1
  reconciledAt: '2023-08-03T20:28:40Z'
  resources:
    - kind: ConfigMap
      name: ingress-nginx-controller
      namespace: ingress-nginx
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: ingress-nginx
      namespace: ingress-nginx
      status: Synced
      version: v1
    - group: apps
      health:
        status: Healthy
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
      status: Synced
      version: v1
    - group: networking.k8s.io
      kind: IngressClass
      name: nginx
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: ingress-nginx
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: ingress-nginx
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: Role
      name: ingress-nginx
      namespace: ingress-nginx
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: ingress-nginx
      namespace: ingress-nginx
      status: Synced
      version: v1
  sourceType: Helm
  summary:
    images:
      - >-
        registry.k8s.io/ingress-nginx/controller:v1.8.1@sha256:e5c4824e7375fcf2a393e1c03c293b69759af37a9ca6abdb91b13d78a93da8bd
  sync:
    comparedTo:
      destination:
        namespace: ingress-nginx
        server: https://kubernetes.default.svc
      source:
        chart: ingress-nginx
        helm:
          parameters:
            - name: controller.admissionWebhooks.enabled
              value: 'false'
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: 4.7.1
    revision: 4.7.1
    status: Synced
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: ingress-nginx
    helm:
      parameters:
        - name: controller.admissionWebhooks.enabled
          value: 'false'
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.7.1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
