apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2023-06-28T22:55:14Z'
  generation: 476
  labels:
    source: internal
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:path: {}
            f:repoURL: {}
            f:targetRevision: {}
          f:syncPolicy:
            .: {}
            f:automated: {}
            f:syncOptions: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2023-06-29T17:15:29Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:automated: {}
              f:retry:
                .: {}
                f:limit: {}
              f:sync:
                .: {}
                f:revision: {}
                f:syncOptions: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:externalURLs: {}
            f:images: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2023-06-29T23:24:52Z'
  name: rabbitmq
  namespace: argocd
  resourceVersion: '16369837'
  uid: eef7e2eb-cb80-4223-9e70-1f527fcc2e01
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/rabbitmq
status:
  health:
    status: Healthy
  history:
    - deployStartedAt: '2023-06-28T23:08:19Z'
      deployedAt: '2023-06-28T23:08:23Z'
      id: 0
      revision: d1498fbbe7e5cde593b8f9345a3724b849aa0121
      source:
        path: rabbitmq
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
    - deployStartedAt: '2023-06-29T12:48:53Z'
      deployedAt: '2023-06-29T12:48:55Z'
      id: 1
      revision: 65398a47321b884c477ec36fb96f888679971e65
      source:
        path: rabbitmq
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
    - deployStartedAt: '2023-06-29T14:57:54Z'
      deployedAt: '2023-06-29T14:57:56Z'
      id: 2
      revision: 6cca8db8c8c17e61fa0a21df3f74c302831dff58
      source:
        path: rabbitmq
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
    - deployStartedAt: '2023-06-29T17:15:29Z'
      deployedAt: '2023-06-29T17:15:31Z'
      id: 3
      revision: 74c1c9e877e4a388185c3e19ffc4ceb4161ba3ed
      source:
        path: rabbitmq
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
  operationState:
    finishedAt: '2023-06-29T17:15:31Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: 74c1c9e877e4a388185c3e19ffc4ceb4161ba3ed
        syncOptions:
          - CreateNamespace=true
    phase: Succeeded
    startedAt: '2023-06-29T17:15:29Z'
    syncResult:
      resources:
        - group: ''
          hookPhase: Running
          kind: Namespace
          message: namespace/rabbitmq unchanged
          name: rabbitmq
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ServiceAccount
          message: serviceaccount/rabbitmq unchanged
          name: rabbitmq
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Secret
          message: secret/rabbit-secret unchanged
          name: rabbit-secret
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ConfigMap
          message: configmap/rabbitmq-config unchanged
          name: rabbitmq-config
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: Role
          message: >-
            role.rbac.authorization.k8s.io/rabbitmq reconciled.
            role.rbac.authorization.k8s.io/rabbitmq unchanged
          name: rabbitmq
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: rbac.authorization.k8s.io
          hookPhase: Running
          kind: RoleBinding
          message: >-
            rolebinding.rbac.authorization.k8s.io/rabbitmq reconciled.
            rolebinding.rbac.authorization.k8s.io/rabbitmq unchanged
          name: rabbitmq
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/rabbitmq unchanged
          name: rabbitmq
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/stream unchanged
          name: stream
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/rabbitmq-management unchanged
          name: rabbitmq-management
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: StatefulSet
          message: statefulset.apps/rabbitmq configured
          name: rabbitmq
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: Ingress
          message: ingress.networking.k8s.io/rabbitmq-ingress configured
          name: rabbitmq-ingress
          namespace: rabbitmq
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 74c1c9e877e4a388185c3e19ffc4ceb4161ba3ed
      source:
        path: rabbitmq
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
  reconciledAt: '2023-06-29T23:24:52Z'
  resources:
    - kind: ConfigMap
      name: rabbitmq-config
      namespace: rabbitmq
      status: Synced
      version: v1
    - kind: Namespace
      name: rabbitmq
      status: Synced
      version: v1
    - kind: Secret
      name: rabbit-secret
      namespace: rabbitmq
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: rabbitmq
      namespace: rabbitmq
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: rabbitmq-management
      namespace: rabbitmq
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: stream
      namespace: rabbitmq
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: rabbitmq
      namespace: rabbitmq
      status: Synced
      version: v1
    - group: apps
      health:
        message: 'partitioned roll out complete: 3 new pods have been updated...'
        status: Healthy
      kind: StatefulSet
      name: rabbitmq
      namespace: rabbitmq
      status: Synced
      version: v1
    - group: networking.k8s.io
      health:
        status: Healthy
      kind: Ingress
      name: rabbitmq-ingress
      namespace: rabbitmq
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: Role
      name: rabbitmq
      namespace: rabbitmq
      status: Synced
      version: v1
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
      name: rabbitmq
      namespace: rabbitmq
      status: Synced
      version: v1
  sourceType: Kustomize
  summary:
    externalURLs:
      - http://rabbitmq.binesty.net/
    images:
      - busybox
      - rabbitmq:3.9-management
  sync:
    comparedTo:
      destination:
        namespace: rabbitmq
        server: https://kubernetes.default.svc
      source:
        path: rabbitmq
        repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
        targetRevision: HEAD
    revision: 74c1c9e877e4a388185c3e19ffc4ceb4161ba3ed
    status: Synced
spec:
  destination:
    namespace: rabbitmq
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: rabbitmq
    repoURL: https://github.com/Binesty/Infrastructure-Kubernetes.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
