# clusterissuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-self-signed
spec:
  selfSigned: {}
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: binesty-certificate
  namespace: cert-manager
spec:
  isCA: true
  duration: 43800h # 5 years
  commonName: "binesty.com"
  dnsNames:
    - "binesty.com"
  secretName: binesty-certificate-key-pair
  privateKey:
    algorithm: ECDSA
    size: 256  
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
    group: cert-manager.io
--- 

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  ca:
    secretName: binesty-certificate-key-pair
---