---
- name: Installing Kubernetes with Containerd
  hosts: all
  become: true

  tasks:
    - name: Upgrade S.O with apt upgrade
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400