apiVersion: v1
kind: Namespace
metadata:
  name: minio
  labels:
    name: minio
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-minio
  namespace: minio
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs
    server: 192.168.0.150
--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-minio
  namespace: minio  
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio-service
  replicas: 2
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9090
        ports:
        - containerPort: 9090        
        volumeMounts:
        - mountPath: /data
          name: nfs-minio
        resources:
          limits:
            cpu: 500m
            memory: 800Mi
          requests:
            cpu: 500m
            memory: 800Mi
      volumes: 
      - name: nfs-minio
        persistentVolumeClaim:
          claimName: nfs-minio            
---

apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
  labels:
    app: minio
spec:
  selector:
    app: minio
  clusterIP: None
  ports:
    - port: 9090
      name: http
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:        
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: minio-ingress
  namespace: minio
spec:
  ingressClassName: nginx
  rules:
  - host: minio.binesty.corp
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-service
            port:
              number: 9090
---
