apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-minio
  namespace: minio  
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---     