apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: kubernetes-replicator
data:
  token: aHZzLk5FRWVjeXVLTHJSQWIwOUxlWDhkYnk2Sg==
---

apiVersion: v1
kind: Secret
metadata:
  name: secret-azure-registry
  namespace: kubernetes-replicator   
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: > 
        use-binesty-registry=true
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJiaW5lc3R5LmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJiaW5lc3R5IiwicGFzc3dvcmQiOiJhbFAzYjBKeTRXdD1SZTN1bEJ2QW1vVVI2azdUNGlycCIsImF1dGgiOiJZbWx1WlhOMGVUcGhiRkF6WWpCS2VUUlhkRDFTWlROMWJFSjJRVzF2VlZJMmF6ZFVOR2x5Y0E9PSJ9fX0=
type: kubernetes.io/dockerconfigjson
---

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-access-cluster-secret-store
  namespace: kubernetes-replicator
spec:
  provider:
    vault:
      server: "http://vault-internal.vault.svc.cluster.local:8200"
      path: "vault"
      version: "v1"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-access-external-secret
  namespace: kubernetes-replicator
  annotations:
    replicator.v1.mittwald.de/replicate-to-matching: > 
      use-vault=true
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-access-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: vault-access-secret
  data:  
  - secretKey: VAULT_ADDRESS
    remoteRef:
      key: access
      property: VAULT_ADDRESS      
  - secretKey: VAULT_TOKEN
    remoteRef:
      key: access
      property: VAULT_TOKEN
  - secretKey: ENVIRONMENT
    remoteRef:
      key: access
      property: ENVIRONMENT      