apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2024-04-03T01:02:28Z'
  generation: 60
  labels:
    source: internal
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:path: {}
            f:repoURL: {}
            f:targetRevision: {}
          f:syncPolicy:
            .: {}
            f:automated: {}
            f:syncOptions: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2024-04-03T01:22:51Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:controllerNamespace: {}
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:username: {}
              f:retry: {}
              f:sync:
                .: {}
                f:prune: {}
                f:revision: {}
                f:syncOptions: {}
                f:syncStrategy:
                  .: {}
                  f:hook:
                    .: {}
                    f:force: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:images: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2024-04-03T01:24:07Z'
  name: databases
  namespace: argocd
  resourceVersion: '123405'
  uid: 2a939475-0bbd-4924-b637-861f805091dc
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/databases
status:
  controllerNamespace: argocd
  health:
    status: Progressing
  history:
    - deployStartedAt: '2024-04-03T01:02:32Z'
      deployedAt: '2024-04-03T01:02:35Z'
      id: 0
      revision: 29a7f183ee43def87f6be56a5b786b0df5f829eb
      source:
        path: cluster/argocd/sources/databases
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    - deployStartedAt: '2024-04-03T01:22:39Z'
      deployedAt: '2024-04-03T01:22:41Z'
      id: 1
      revision: 7ec77baa7129f74ce4a93ff928a64d5ea6bf22ac
      source:
        path: cluster/argocd/sources/databases
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    - deployStartedAt: '2024-04-03T01:22:51Z'
      deployedAt: '2024-04-03T01:22:53Z'
      id: 2
      revision: 7ec77baa7129f74ce4a93ff928a64d5ea6bf22ac
      source:
        path: cluster/argocd/sources/databases
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
  operationState:
    finishedAt: '2024-04-03T01:22:53Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        prune: true
        revision: 7ec77baa7129f74ce4a93ff928a64d5ea6bf22ac
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - Replace=true
        syncStrategy:
          hook:
            force: true
    phase: Succeeded
    startedAt: '2024-04-03T01:22:51Z'
    syncResult:
      resources:
        - group: ''
          hookPhase: Running
          kind: PersistentVolumeClaim
          message: |-
            persistentvolumeclaim "postgres-pvc" deleted
            persistentvolumeclaim/postgres-pvc replaced
          name: postgres-pvc
          namespace: databases
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: |-
            service "postgres" deleted
            service/postgres replaced
          name: postgres
          namespace: databases
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: |-
            service "sql-server-service" deleted
            service/sql-server-service replaced
          name: sql-server-service
          namespace: databases
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: StatefulSet
          message: |-
            statefulset.apps "sql-server" deleted
            statefulset.apps/sql-server replaced
          name: sql-server
          namespace: databases
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: StatefulSet
          message: |-
            statefulset.apps "postgres" deleted
            statefulset.apps/postgres replaced
          name: postgres
          namespace: databases
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 7ec77baa7129f74ce4a93ff928a64d5ea6bf22ac
      source:
        path: cluster/argocd/sources/databases
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
  reconciledAt: '2024-04-03T01:22:54Z'
  resources:
    - health:
        status: Healthy
      kind: PersistentVolumeClaim
      name: postgres-pvc
      namespace: databases
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: postgres
      namespace: databases
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: sql-server-service
      namespace: databases
      status: Synced
      version: v1
    - group: apps
      health:
        message: 'partitioned roll out complete: 1 new pods have been updated...'
        status: Healthy
      kind: StatefulSet
      name: postgres
      namespace: databases
      status: Synced
      version: v1
    - group: apps
      health:
        message: Waiting for 1 pods to be ready...
        status: Progressing
      kind: StatefulSet
      name: sql-server
      namespace: databases
      status: Synced
      version: v1
  sourceType: Kustomize
  summary:
    images:
      - mcr.microsoft.com/mssql/server:2019-latest
      - postgres:13
  sync:
    comparedTo:
      destination:
        namespace: databases
        server: https://kubernetes.default.svc
      source:
        path: cluster/argocd/sources/databases
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    revision: 7ec77baa7129f74ce4a93ff928a64d5ea6bf22ac
    status: Synced
spec:
  destination:
    namespace: databases
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: cluster/argocd/sources/databases
    repoURL: git@github.com:Binesty/Kubernetes.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
