apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2024-04-03T01:35:45Z'
  generation: 11
  labels:
    source: internal
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:source: {}
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:path: {}
            f:repoURL: {}
            f:targetRevision: {}
          f:syncPolicy:
            .: {}
            f:automated: {}
            f:syncOptions: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2024-04-03T01:37:32Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:controllerNamespace: {}
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:automated: {}
              f:retry:
                .: {}
                f:limit: {}
              f:sync:
                .: {}
                f:revision: {}
                f:syncOptions: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:images: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:path: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2024-04-03T01:37:35Z'
  name: databases
  namespace: argocd
  resourceVersion: '127899'
  uid: e1075755-475f-412e-b6b2-e8320a44420a
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/databases
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
    - deployStartedAt: '2024-04-03T01:35:47Z'
      deployedAt: '2024-04-03T01:35:48Z'
      id: 0
      revision: 33e658e040ec1f3ced4d90a2cf78aff9f84882dd
      source:
        path: cluster/argocd/sources/databases
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
  operationState:
    finishedAt: '2024-04-03T01:35:48Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: 33e658e040ec1f3ced4d90a2cf78aff9f84882dd
        syncOptions:
          - CreateNamespace=true
    phase: Succeeded
    startedAt: '2024-04-03T01:35:47Z'
    syncResult:
      resources:
        - group: ''
          hookPhase: Running
          kind: PersistentVolumeClaim
          message: persistentvolumeclaim/postgres-pvc created
          name: postgres-pvc
          namespace: databases
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/postgres created
          name: postgres
          namespace: databases
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: StatefulSet
          message: statefulset.apps/postgres created
          name: postgres
          namespace: databases
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 33e658e040ec1f3ced4d90a2cf78aff9f84882dd
      source:
        path: cluster/argocd/sources/databases
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
  reconciledAt: '2024-04-03T01:35:48Z'
  resources:
    - health:
        status: Healthy
      kind: PersistentVolumeClaim
      name: postgres-pvc
      namespace: databases
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: postgres
      namespace: databases
      status: Synced
      version: v1
    - group: apps
      health:
        message: 'partitioned roll out complete: 1 new pods have been updated...'
        status: Healthy
      kind: StatefulSet
      name: postgres
      namespace: databases
      status: Synced
      version: v1
  sourceType: Kustomize
  summary:
    images:
      - postgres:13
  sync:
    comparedTo:
      destination:
        namespace: databases
        server: https://kubernetes.default.svc
      source:
        path: cluster/argocd/sources/databases
        repoURL: git@github.com:Binesty/Kubernetes.git
        targetRevision: main
    revision: 33e658e040ec1f3ced4d90a2cf78aff9f84882dd
    status: Synced
spec:
  destination:
    namespace: databases
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: cluster/argocd/sources/databases
    repoURL: git@github.com:Binesty/Kubernetes.git
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
