apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: '2024-04-10T17:36:20Z'
  generation: 133
  managedFields:
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:destination:
            .: {}
            f:namespace: {}
            f:server: {}
          f:project: {}
          f:source:
            .: {}
            f:chart: {}
            f:helm:
              .: {}
              f:parameters: {}
            f:repoURL: {}
            f:targetRevision: {}
          f:syncPolicy:
            .: {}
            f:syncOptions: {}
        f:status:
          .: {}
          f:health: {}
          f:summary: {}
          f:sync:
            .: {}
            f:comparedTo:
              .: {}
              f:destination: {}
              f:source: {}
      manager: argocd-server
      operation: Update
      time: '2024-04-10T17:58:43Z'
    - apiVersion: argoproj.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:controllerNamespace: {}
          f:health:
            f:status: {}
          f:history: {}
          f:operationState:
            .: {}
            f:finishedAt: {}
            f:message: {}
            f:operation:
              .: {}
              f:initiatedBy:
                .: {}
                f:automated: {}
              f:retry:
                .: {}
                f:limit: {}
              f:sync:
                .: {}
                f:revision: {}
                f:syncOptions: {}
            f:phase: {}
            f:startedAt: {}
            f:syncResult:
              .: {}
              f:resources: {}
              f:revision: {}
              f:source:
                .: {}
                f:chart: {}
                f:helm:
                  .: {}
                  f:parameters: {}
                f:repoURL: {}
                f:targetRevision: {}
          f:reconciledAt: {}
          f:resources: {}
          f:sourceType: {}
          f:summary:
            f:externalURLs: {}
            f:images: {}
          f:sync:
            f:comparedTo:
              f:destination:
                f:namespace: {}
                f:server: {}
              f:source:
                f:chart: {}
                f:helm:
                  .: {}
                  f:parameters: {}
                f:repoURL: {}
                f:targetRevision: {}
            f:revision: {}
            f:status: {}
      manager: argocd-application-controller
      operation: Update
      time: '2024-04-10T22:41:39Z'
  name: minio
  namespace: argocd
  resourceVersion: '851997'
  uid: 4c11fae2-43fe-43aa-9a04-4218c72191c2
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/minio
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
    - deployStartedAt: '2024-04-10T17:36:21Z'
      deployedAt: '2024-04-10T17:36:23Z'
      id: 0
      revision: 14.1.7
      source:
        chart: minio
        helm:
          parameters:
            - name: ingress.enabled
              value: 'true'
            - name: ingress.hostname
              value: minio.binesty.corp
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 14.1.7
    - deployStartedAt: '2024-04-10T17:58:43Z'
      deployedAt: '2024-04-10T17:58:44Z'
      id: 1
      revision: 14.1.7
      source:
        chart: minio
        helm:
          parameters:
            - name: ingress.enabled
              value: 'true'
            - name: ingress.hostname
              value: minio.binesty.corp
            - name: ingress.ingressClassName
              value: nginx
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 14.1.7
  operationState:
    finishedAt: '2024-04-10T17:58:44Z'
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: 14.1.7
        syncOptions:
          - CreateNamespace=true
    phase: Succeeded
    startedAt: '2024-04-10T17:58:43Z'
    syncResult:
      resources:
        - group: networking.k8s.io
          hookPhase: Running
          kind: NetworkPolicy
          message: networkpolicy.networking.k8s.io/minio configured
          name: minio
          namespace: minio
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: ServiceAccount
          message: serviceaccount/minio unchanged
          name: minio
          namespace: minio
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Secret
          message: secret/minio configured
          name: minio
          namespace: minio
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: PersistentVolumeClaim
          message: persistentvolumeclaim/minio unchanged
          name: minio
          namespace: minio
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ''
          hookPhase: Running
          kind: Service
          message: service/minio configured
          name: minio
          namespace: minio
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          kind: Deployment
          message: deployment.apps/minio configured
          name: minio
          namespace: minio
          status: Synced
          syncPhase: Sync
          version: v1
        - group: networking.k8s.io
          hookPhase: Running
          kind: Ingress
          message: ingress.networking.k8s.io/minio configured
          name: minio
          namespace: minio
          status: Synced
          syncPhase: Sync
          version: v1
      revision: 14.1.7
      source:
        chart: minio
        helm:
          parameters:
            - name: ingress.enabled
              value: 'true'
            - name: ingress.hostname
              value: minio.binesty.corp
            - name: ingress.ingressClassName
              value: nginx
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 14.1.7
  reconciledAt: '2024-04-10T22:41:39Z'
  resources:
    - health:
        status: Healthy
      kind: PersistentVolumeClaim
      name: minio
      namespace: minio
      status: Synced
      version: v1
    - kind: Secret
      name: minio
      namespace: minio
      status: Synced
      version: v1
    - health:
        status: Healthy
      kind: Service
      name: minio
      namespace: minio
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: minio
      namespace: minio
      status: Synced
      version: v1
    - group: apps
      health:
        status: Healthy
      kind: Deployment
      name: minio
      namespace: minio
      status: Synced
      version: v1
    - group: networking.k8s.io
      health:
        status: Healthy
      kind: Ingress
      name: minio
      namespace: minio
      status: Synced
      version: v1
    - group: networking.k8s.io
      kind: NetworkPolicy
      name: minio
      namespace: minio
      status: Synced
      version: v1
  sourceType: Helm
  summary:
    externalURLs:
      - http://minio.binesty.corp/
    images:
      - docker.io/bitnami/minio:2024.4.6-debian-12-r0
  sync:
    comparedTo:
      destination:
        namespace: minio
        server: https://kubernetes.default.svc
      source:
        chart: minio
        helm:
          parameters:
            - name: ingress.enabled
              value: 'true'
            - name: ingress.hostname
              value: minio.binesty.corp
            - name: ingress.ingressClassName
              value: nginx
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 14.1.7
    revision: 14.1.7
    status: Synced
spec:
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    chart: minio
    helm:
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: ingress.hostname
          value: minio.binesty.corp
        - name: ingress.ingressClassName
          value: nginx
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.1.7
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
